apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:

      - name: review-service
        image: eu.gcr.io/sixth-spot-273818/IMAGE:TAG
        env:
          - name: BT_SERVER
            value: kafka-broker:9092
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m              